version: '3.8'

services:
  backend:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-investment.cn88ie2ekh9s.ap-northeast-2.rds.amazonaws.com:3306/investment
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: sosow0212
      SPRING_APPLICATION_NAME: investment
      NAVER_API_CLIENT_ID: BZHPyuv5UKyJZBNmnAC5
      NAVER_API_CLIENT_SECRET: sZyKuW0Y9j
      SERVICE_KEY: 6vkAL8btLG4h51Af2JRQ5LUXImyRng8XzbfVmG1K7n2Vw0sY0D6BZmVUkVghiGzoR5pAHvnKdL5Xmrtw2fXDZw==
      API_TR_ID: FHPST01710000
      API_APP_SECRET: LP32aRtDpu78NKf0ihybuysDXfYKh6Sjz/n3kEKioIN7Q9cWN9OST6s+fZ64BTluO5Fl3d0tQJNB4qdjsrL8Q2AekG+7Aifa+bwcY1xpfoKx/PjdtLnEcg/gnlttQaP64fZjmP2RCOxKnRUT0jr8RhSMeu5Q3U2tc9hqjpm66RiGJ0BFtwU=
      API_APP_KEY: PSklHGvwDtk1k3oReEkR6M5lUDDsYTTtys8m
      API_ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImZjNGFjNmRkLWVhMGEtNDZhMC1hNGE1LTEyOTJhMTQyNDI1MSIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTcyODIwODQyNiwiaWF0IjoxNzI4MTIyMDI2LCJqdGkiOiJQU2tsSEd2d0R0azFrM29SZUVrUjZNNWxVRERzWVRUdHlzOG0ifQ.8HFKmJRJNb3DGGnP5onOWtBuc6txZ9-Bo3xyE4l-UFaY5xmnIhGGKa7C01tf_BhuZu6F5Jf7DC8Zey1M9X_7oA
      API_APPROVAL_KEY: 85337d24-1d88-4793-acbd-3202ae289251
      MARKET_CAPITALIZATION_TR_ID: FHPST01740000
      FLUCTUATION_TR_ID: FHPST01700000
      FINANCIAL_RATIO_TR_ID: FHKST66430300
      CONSENSUS_TR_ID: FHKST663300C0
      STOCK_TR_ID: FHKST01010100
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
    ports:
      - 8080:8080
