version: '3.8'

services:
  backend:
    build: .
    restart: always
    environment:

      NAVER_API_CLIENTID: BZHPyuv5UKyJZBNmnAC5
      NAVER_API_KEY: ObqWvGnX7F
      # ??? API
      SERVICEKEY: 6vkAL8btLG4h51Af2JRQ5LUXImyRng8XzbfVmG1K7n2Vw0sY0D6BZmVUkVghiGzoR5pAHvnKdL5Xmrtw2fXDZw==
      # API ??
      API_TRID: HPST01710000
      API_APP_SECRET: LP32aRtDpu78NKf0ihybuysDXfYKh6Sjz/n3kEKioIN7Q9cWN9OST6s+fZ64BTluO5Fl3d0tQJNB4qdjsrL8Q2AekG+7Aifa+bwcY1xpfoKx/PjdtLnEcg/gnlttQaP64fZjmP2RCOxKnRUT0jr8RhSMeu5Q3U2tc9hqjpm66RiGJ0BFtwU=
      API_APP_KEY: PSklHGvwDtk1k3oReEkR6M5lUDDsYTTtys8m
      API_ACCESS_TOKEN: yJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImRiNGZmNjUzLWQ1ZWQtNGIwOS1hOTY4LTk0ZDlhZTdiMzlhMyIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc0MTg1ODM5OSwiaWF0IjoxNzQxNzcxOTk5LCJqdGkiOiJQU2tsSEd2d0R0azFrM29SZUVrUjZNNWxVRERzWVRUdHlzOG0ifQ.ppQexDeu5JIHausIG_ry4c0MuMzz2IYYxKxJd8MWqd99GysXOuxZUuHldyqQeMX6Uf24ZxjQ3e889KFv_a0UXw
      API_APPROVAL_KEY: 85337d24-1d88-4793-acbd-3202ae289251®
      # API ???? ID
      MARKET_TR_ID: FHPST01740000
      FLUCTUATION_TR_ID: FHPST01700000
      FINANCIAL_TR_ID: FHKST66430300
      CONSENSUS_TR_ID: FHKST663300C0
      STOCK_TR_ID: FHKST01010100
      CHART_TR_ID: FHKST03010100
      WEBSOCKET_KEY: "48121c9e-dcbc-47f3-89c7-0282fecc077d"
      # DB ??
      spring.datasource.url: jdbc:mysql://database-investment.cn88ie2ekh9s.ap-northeast-2.rds.amazonaws.com:3306/investment
      spring.datasource.username: admin
      spring.datasource.password: sosow0212
      spring.jpa.hibernate.ddl-auto: update
      spring.jpa.show-sql: true
      # Oauth2 google
      GOOGLE_OAUTH_CLIENT_ID: ${{secrets.GOOGLE_OAUTH_CLIENT_ID }}
      GOOGLE_OAUTH_CLIENT_SECRET: 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
      GOOGLE_OAUTH_SCOPE: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      GOOGLE_OAUTH_REDIRECTION_URL: https://growfolio-nu.vercel.app/api/google/callback
      # security ?? ??? ????
      spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      spring.data.redis.host: localhost
      spring.data.redis.port: 6379
      spring.data.redis.password:
      spring.data.redis.timeout: 2000

    ports:
      - 8080:8080
