name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image
        run: |
          docker build -t seungboong/stockservice .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push to ECR
        run: |
          IMAGE_REPO=864899864038.dkr.ecr.ap-northeast-2.amazonaws.com/stockrepo
          docker tag seungboong/stockservice:latest $IMAGE_REPO:latest
          docker push $IMAGE_REPO:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 13.209.73.178
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }} # GitHub Secrets에 SSH 키 저장
          script: |
            # Stop and remove the existing container
            docker stop stockservice || true
            docker rm stockservice || true
            # Pull the latest image from ECR
            docker pull 864899864038.dkr.ecr.ap-northeast-2.amazonaws.com/stockrepo:latest
            # Run the new container
            docker run -d --name stockservice -p 8080:8080 864899864038.dkr.ecr.ap-northeast-2.amazonaws.com/stockrepo:latest

