name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v2
      
      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. application.properties 파일 생성 및 환경 변수 적용
      - name: Create application.properties
        run: |
          mkdir -p ./src/main/resources  # 디렉토리가 없을 경우 생성
          touch ./src/main/resources/application.properties  # 파일 생성
          echo "api.access_token=***
          api.app_key=***
          api.app_secret=***
          " > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties
      # 4. Gradle Wrapper 파일에 실행 권한 부여 (investement 디렉토리)
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./investement

      # 5. application.properties에서 API_ACCESS_TOKEN 덮어쓰기
      - name: Update API_ACCESS_TOKEN in application.properties
        run: |
          sed -i 's/^api.access_token=.*/api.access_token=${{ secrets.API_ACCESS_TOKEN }}/' ./investement/src/main/resources/application.properties

      # 6. Gradle 빌드 실행 (investement 디렉토리)
      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./investement

      # 7. Docker 이미지 빌드 (investement 디렉토리에서 실행)
      - name: Build Docker image
        run: docker build -t seungboong/stockservice ./investement

      # 8. AWS ECR에 로그인 (AWS CLI 사용)
      - name: Log in to Amazon ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-northeast-2
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 864899864038.dkr.ecr.ap-northeast-2.amazonaws.com

      # 9. Docker 이미지 태그 및 ECR로 푸시
      - name: Tag and push to ECR
        run: |
          IMAGE_REPO=864899864038.dkr.ecr.ap-northeast-2.amazonaws.com/stockrepo
          docker tag seungboong/stockservice:latest $IMAGE_REPO:latest
          docker push $IMAGE_REPO:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 10. EC2 서버에 SSH로 접속하여 배포
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 13.209.73.178
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}  # GitHub Secrets에 저장된 SSH 키 사용
          script: |
           docker stop stockservice || true
           docker rm stockservice || true
           docker pull 864899864038.dkr.ecr.ap-northeast-2.amazonaws.com/stockrepo:latest
           docker run -d --name stockservice -p 8080:8080 864899864038.dkr.ecr.ap-northeast-2.amazonaws.com/stockrepo:latest
