name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 자동으로 배포가 실행됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up SSH for EC2 access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ec2-13-125-177-110.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@13.125.177.110 "your-deployment-command"
